In [1]:
[[123,12,123,12,33],[]]

[[123, 12, 123, 12, 33], []]

In [19]:
import numpy as np

In [3]:
n = np.arange(27)

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [2]:
import cv2

In [9]:
# converts an image into a vector, use 0 for grayscale or 1 for rbg
im_g = cv2.imread("./data/smallgray.png",0)

In [10]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
cv2.imwrite("normalgray.png",im_g)

True

#### Indexing, slicing and iterating numpy arrays

In [11]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [12]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [13]:
# iterating over a numpy array
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [14]:
# to iterate through columns I must access a transposed version
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [16]:
# If I want to iterate element by element
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


#### Stacking and splitting numpy arrays

In [27]:
# to stack I must have arrays with the same dimension

In [17]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
# to stack arrays horizontally
ims=np.hstack((im_g,im_g))


array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
# to stack vertically
imv=np.vstack((im_g,im_g))

In [26]:
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
# to split an array it must result in an equal division
split= np.vsplit(ims,3)

In [29]:
split

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]